# Generated by Django 4.0.6 on 2022-07-09 19:58

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_consent', '0002_auto__add_logitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('description',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='cookiegroup',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
